version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: student
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
